language: objective-c
osx_image: xcode8.2

install:
  - carthage bootstrap --platform iOS

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - xcodebuild build test -scheme Cryptobox-ios -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
