name: Merge PR

on: 
  issue_comment:
    types: [created]

jobs:
  create_comment:
    runs-on: ubuntu-latest
  call-workflow:
    uses: wireapp/wire-ios-shared-resources/.github/workflows/mergePR.yml@master
