name: Merge PR

on: 
  issue_comment:
    types: [created]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: merge spell
        uses: wireapp/mergeSpell@0.1.5
