name: Dispatch new release v0.2

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: tell downstream(s) repo this repo published a new release
        run: |
          curl -X POST https://api.github.com/repos/wireapp/wire-ios-data-model/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ZENKINS_WORKFLOW_PAT }}" \
          --data '{"event_type": "newRelease", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

          curl -X POST https://api.github.com/repos/wireapp/wire-ios-mocktransport/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ZENKINS_WORKFLOW_PAT }}" \
          --data '{"event_type": "newRelease", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
