name: Ask Zenkins to review PR

on: 
  issue_comment:
    types: [created]
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: guard for magic spell
        if: ${{ github.event.comment.body != '@zenkins review' }}
        run: exit 1

      - name: Review bump components PR
        run: |
          gh pr review ${{ github.event.issue.number }} --approve -R wireapp/wire-ios-mocktransport
