name: review PR by Zenkins v0.1

on: 
  issue_comment:
    types: [created]
jobs:
  review:
    runs-on: ubuntu-latest
#     env:
#       GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}

    steps:
      - name: guard for magic spell
        if: ${{ github.event.comment.body != '@zenkins review' }}
        run: exit 1

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.DISPATCH_TOKEN }}
          number: ${{ github.event.issue.number }}
