name: review PR by Zenkins

on: 
  issue_comment:
    types: [created]
jobs:
  review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}

    steps:
      - name: guard for magic spell
        if: ${{ github.event.comment.body != '@zenkins review' }}
        run: exit 1

      - name: Review bump components PR
        run: |
          gh auth login --with-token < ${{ secrets.DISPATCH_TOKEN }}
          gh pr review ${{ github.event.issue.number }} --approve -R wireapp/wire-ios-mocktransport
